# ==========================================
# Cabinet360 Core Service Configuration
# ==========================================

# ---------------------------
# Application Info
# ---------------------------
spring:
  application:
    name: core-service

  # ---------------------------
  # Database Configuration
  # ---------------------------
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:core_service_db}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver

    # Connection Pool (HikariCP)
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # ---------------------------
  # JPA/Hibernate Configuration
  # ---------------------------
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # ---------------------------
  # Email Configuration
  # ---------------------------
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}
    from: ${SPRING_MAIL_FROM:noreply@cabinet360.com}

  # ---------------------------
  # Security Configuration
  # ---------------------------
  security:
    require-ssl: false

  # ---------------------------
  # Liquibase Configuration (DISABLED)
  # ---------------------------
  liquibase:
    enabled: false

# ---------------------------
# Server Configuration
# ---------------------------
server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
  compression:
    enabled: true

# ---------------------------
# Logging Configuration
# ---------------------------
logging:
  level:
    org.hibernate.SQL: ${LOG_SQL:DEBUG}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOG_SQL_PARAMS:TRACE}
    com.cabinet360.core: DEBUG
    root: ${LOG_LEVEL:INFO}
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: ${LOG_FILE:./logs/core-service.log}

# ---------------------------
# JWT Configuration
# ---------------------------
jwt:
  secret: ${JWT_SECRET:cabinet360supersecurekeymustbeatleast32chars!}
  expiration: ${JWT_EXPIRATION:86400000}

# ---------------------------
# External Services
# ---------------------------
auth:
  service:
    url: ${AUTH_SERVICE_URL:http://auth-service:8080}

# ---------------------------
# CORS Configuration
# ---------------------------
cors:
  origin: ${CORS_ORIGIN:http://localhost:4200,http://localhost:3000}

# ---------------------------
# Support & Admin
# ---------------------------
support:
  email: ${SUPPORT_EMAIL:support@cabinet360.com}

admin:
  email: ${ADMIN_EMAIL:admin@cabinet360.com}
  password: ${ADMIN_PASSWORD:NawfalAdmin2025!}

# ---------------------------
# Twilio SMS Configuration
# ---------------------------
twilio:
  account:
    sid: ${TWILIO_ACCOUNT_SID:}
  auth:
    token: ${TWILIO_AUTH_TOKEN:}
  phone:
    number: ${TWILIO_PHONE_NUMBER:}
  enabled: ${TWILIO_ENABLED:true}

# ---------------------------
# Notification Settings
# ---------------------------
notification:
  batch:
    size: ${NOTIFICATION_BATCH_SIZE:50}

email:
  batch:
    delay: ${EMAIL_BATCH_DELAY:1000}

sms:
  batch:
    delay: ${SMS_BATCH_DELAY:1000}

# ---------------------------
# Management/Actuator
# ---------------------------
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  health:
    defaults:
      enabled: true

---
# ==========================================
# DEVELOPMENT PROFILE
# ==========================================
spring:
  config:
    activate:
      on-profile: dev

  # Development Database
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:core_service_db}_dev
    hikari:
      maximum-pool-size: 5

  # Development JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# Development Logging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.cabinet360.core: DEBUG
    root: DEBUG

---
# ==========================================
# TEST PROFILE
# ==========================================
spring:
  config:
    activate:
      on-profile: test

  # Test Database (H2 in-memory)
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  # Test JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false

  # H2 Console for debugging
  h2:
    console:
      enabled: true
      path: /h2-console

# Test Logging
logging:
  level:
    org.hibernate.SQL: WARN
    com.cabinet360.core: INFO
    root: WARN

# Test JWT
jwt:
  secret: testsecretkey32characterslongfortest
  expiration: 3600000

---
# ==========================================
# PRODUCTION PROFILE
# ==========================================
spring:
  config:
    activate:
      on-profile: prod

  # Production Database
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  # Production JPA
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

# Production Logging
logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    com.cabinet360.core: INFO
    root: WARN
  file:
    name: /var/log/cabinet360/core-service.log

# Production Security
management:
  endpoint:
    health:
      show-details: never